generate logfile and test results

diff --git a/.github/workflows/docker-image.yml b/.github/workflows/docker-image.yml
--- a/.github/workflows/docker-image.yml
+++ b/.github/workflows/docker-image.yml
@@ -18,18 +18,33 @@ jobs:
         name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
       -
+        name: Generate Log File
+        run: |
+          echo "$(date --iso-8601=minutes)" > /tmp/log.txt
+          echo "Eran Krakovsky, Noa Landau" >> /tmp/log.txt
+      -
         name: Build and export
         uses: docker/build-push-action@v4
         with:
           context: .
           tags: cloud-hw3:latest
           outputs: type=docker,dest=/tmp/cloud-hw3.tar
+      - 
+        name: save build log
+        run: |
+          if [ $? -eq 0 ]; then
+            echo "image successfully built" >> /tmp/log.txt
+          else
+            echo "image not able to be built" >> /tmp/log.txt
+          fi
       -
         name: Upload artifact
         uses: actions/upload-artifact@v3
         with:
-          name: myimage
-          path: /tmp/cloud-hw3.tar
+            name: results
+            path: |
+              /tmp/cloud-hw3.tar
+              /tmp/log.txt
 
   test:
     runs-on: ubuntu-latest
@@ -45,7 +60,7 @@ jobs:
         name: Download artifact
         uses: actions/download-artifact@v3
         with:
-          name: myimage
+          name: results
           path: /tmp
       -
         name: Load image
@@ -63,4 +78,17 @@ jobs:
       -
         name: Run tests
         run: |
-          pytest tests/tests.py
+          pytest tests/tests.py -v > /tmp/test_log.txt
+          if [ $? -eq 0 ]; then
+            echo "tests succeeded" >> /tmp/log.txt
+          else
+            echo "tests failed" >> /tmp/log.txt
+          fi
+      -
+        name: Upload artifact
+        uses: actions/upload-artifact@v3
+        with:
+            name: results
+            path: |
+              /tmp/test_log.txt
+              /tmp/log.txt
